### ISSUE TITLE
README link to User Guide results in Page Not Found

### ISSUE THREAD

**Issue by keturn** [ioflo/ioflo#21]
The README (which renders in GitHub) says the User Guide is at http://ioflo.com/documentation/user-guide/

It is not.

**Comment by SmithSamuelM** [comment]
sorry will fix the link

https://github.com/ioflo/ioflo_manuals <https://github.com/ioflo/ioflo_manuals>

> On 01 Sep 2015, at 13:52 , Kevin Turner <notifications@github.com> wrote:
> 
> The README (which renders in GitHub) says the User Guide is at http://ioflo.com/documentation/user-guide/ <http://ioflo.com/documentation/user-guide/>
> It is not.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ioflo/ioflo/issues/21>.
> 


Samuel M. Smith Ph.D.
smith.samuel.m@gmail.com

242 East 600 North, Lindon Utah 84042-1662 USA
801-785-3185 home
801-592-8230 mobile
801-766-3528 fax

**Comment by SmithSamuelM** [comment]
fixed
