### ISSUE TITLE
Iterate over a list

### ISSUE THREAD

**Issue by dkhan11** [ioflo/ioflo#27]
Hi and thank you for this interesting software,

I have reviewed your documentation and I'm trying to understand if it is possible to have a field which is a list of some sort:
"set targets to A B C D"

And if so, is there a way to iterate over them with something like 'for'? I assume that I can use 'repeat' but I need to know the length of the list...
If the answer is no, how complicated is it to create my own python implementation of this?

Thanks in advance,
DD.

**Comment by SmithSamuelM** [comment]
Floscript is meant to manage context.  The task you describe of iterating over a list is best done in a behavior/action run by FloScript not with Floscript.
You would write the behavior in python. and then run it using the Floscript "do" verb.

Although FloScript has a repeat verb this is just for repeating a given set of actions in a context not to do lower level tasks like iterating over a list.

**Comment by dkhan11** [comment]
Got it, thanks! I must admit that I was unable to find a python example that works...
Thanks again,
DD.

**Comment by SmithSamuelM** [comment]
I will post a simple tutorial on writing a behavior.

**Comment by dkhan11** [comment]
Thank you!!!
